config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get 'quit'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :shops do
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :genre, optional: true
  has_many :reviews, dependent: :destroy
  has_many :shop_images, dependent: :destroy
  accepts_attachments_for :shop_images, attachment: :image

  geocoded_by :address #addressカラムを基準に緯度経度を算出する
  after_validation :geocode, if: :address_changed? #住所変更時に緯度経度も変更する

  enum prefecture:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :prefecture, presence: true
  validates :address, presence: true
  validates :zipcode, presence: true
  validates :phonenumber, presence: true
  validates :regular_holiday, presence: true
  validates :opning_hours, presence: true
  validates :acsess, presence: true
  validates :parking, presence: true
  validates :seats, presence: true
  validates :genre_id, presence: true

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy]
  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
     redirect_to shop_path(@shop.id), notice:"登録しました"
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params)
    redirect_to shop_path(@shop.id), notice:"更新しました"
  end

  def show
    @shop = Shop.find(params[:id])
    genre_list = {
     "---":0,
     居酒屋:1,カレー:2,ラーメン:3,焼き肉:4,カフェ:5,鍋:6,寿司:7,
     魚介・海鮮:8,焼き鳥・鳥料理:9,和食:10,天ぷら:11,うどん・そば:12,すき焼き・しゃぶしゃぶ:13,おでん:14,
     お好み焼き・たこ焼き:15,ステーキ・ハンバーグ:16,鉄板焼:17,パスタ・ピザ:18,ハンバーガー:19,洋食:20,
     フレンチ:21,イタリアン:22,西洋各国料理:23,中華料理:24,
     韓国料理:25,バー:26,ファミレス:27,定食:28,丼もの:29,その他:30,
   }
    genre_list.map{|genre| @genre_name = genre[0] if genre[1] == @shop.genre_id}
    
    # レビューの平均点
    if @shop.reviews.blank?
      @average_review = 0
    else
      @average_review = @shop.reviews.average(:rate)
    end

    @shop_images = @shop.shop_images
  end

  def index
    @shops = Shop.all
    if @search
      @shops = @search.result(distinct: true)

    end

  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    flash[:success] = '店舗を削除しました。'
    redirect_to shops_path
  end


  private

  def shop_params
    params.require(:shop).permit(:name,:name_kana,:prefecture, :address, :zipcode ,:phonenumber,
    :hp, :regular_holiday, :opning_hours, :acsess, :parking, :seats, :payment, :facility, :genre_id, shop_images_images: [] )
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/edit.html.erb
<div class="container contents">
 <h1 class"heading">店舗編集</h1>
 <p>店舗登録の協力をお願いします。</br>
 入力項目が多数あるので、不明な箇所は未入力のままでも登録できます。</br>
 一度店舗を登録した後はユーザーなら誰でも情報を編集することができます。</br>
 既に同じ店舗が登録されている場合は後から登録したページは削除されますのでご注意ください。</p>
 <%= form_with model: @shop, local: true do |f| %>
 <table class="table">
  <%= render 'layouts/error_messages', model: f.object %>
  <tr>
   <th><%= f.label :name, "店名" %></th>
   <td><%= f.text_field :name, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :name_kana, "店名（かな）" %></th>
   <td><%= f.text_field :name_kana, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :prefecture, "都道府県" %></th>
   <td><%= f.select :prefecture, Shop.prefectures.keys, {} %></td>
  </tr>
  <tr>
   <th><%= f.label :genre_id, "ジャンル" %></th>
   <td>
    <%= f.select :genre_id, {
      "---":0,
      居酒屋:1,カレー:2,ラーメン:3,焼き肉:4,カフェ:5,鍋:6,寿司:7,
      魚介・海鮮:8,焼き鳥・鳥料理:9,和食:10,天ぷら:11,うどん・そば:12,すき焼き・しゃぶしゃぶ:13,おでん:14,
      お好み焼き・たこ焼き:15,ステーキ・ハンバーグ:16,鉄板焼:17,パスタ・ピザ:18,ハンバーガー:19,洋食:20,
      フレンチ:21,イタリアン:22,西洋各国料理:23,中華料理:24,
      韓国料理:25,バー:26,ファミレス:27,定食:28,丼もの:29,その他:30,
    }, {} %>
   </td>
  </tr>
  <tr>
   <th><%= f.label :zipcode, "郵便番号" %></th>
   <td><%= f.text_field :zipcode, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :address, "住所" %></th>
   <td><%= f.text_field :address, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :phonenumber, "TEL" %></th>
   <td><%= f.text_field :phonenumber, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :hp, "HP" %></th>
   <td><%= f.text_field :hp, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :regular_holiday, "定休日" %></th>
   <td><%= f.text_field :regular_holiday, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :opning_hours, "営業時間" %></th>
   <td><%= f.text_area :opning_hours, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :acsess, "アクセス" %></th>
   <td><%= f.text_field :acsess, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :parking, "駐車場" %></th>
   <td><%= f.text_field :parking, class: "form-control" %></td>
  </tr>
  <tr>
   <th><%= f.label :seats, "座席数" %></th>
   <td><%= f.text_field :seats, class: "form-control" %></td>
  </tr>
  <tr>
   <th>画像</th>
   <td><%= f.attachment_field :shop_images_images, multiple: true %></td>
  </tr>
  <tr>
   <th><%= f.submit %></th>
   <td><%= link_to "店舗削除", shop_path(@shop), method: :delete %></td>
  </tr>
 </table>
 <% end %>
</div>

app/views/shops/index.html.erb
<article id ="index">
  <div class="container contents">
    <div class="row">
      <section class="restaurants col-md-12">
        <h2>店舗一覧</h2>
        <div class="row">
          <% @shops.each do |shop| %>
          <div class="content col-md-3">
            <p><% if shop.shop_images.present? %>
          <% shop.shop_images.first(1).each do |image| %>
          <%= attachment_image_tag image, :image, size: "200x150" %>
        <% end %>
        <% else %>
        <%= image_tag 'no_image.jpg', size: '200x150' %>
      <% end %></p>
            <p>店名：<%= shop.name %></p>

            <p>住所：<%= shop.address %></p>

            <p><%= link_to shop_path(shop) do %>
              詳細を見る
              <% end %></p>
            </div>
            <% end %>
          </div>
        </section>
      </div>
    </div>

app/views/shops/new.html.erb
<div class="container contents">

<h1>店舗登録</h1>
<p>店舗登録の協力をお願いします。</br>
入力項目が多数あるので、不明な箇所は未入力のままでも登録できます。</br>
一度店舗を登録した後はユーザーなら誰でも情報を編集することができます。</br>
既に同じ店舗が登録されている場合は後から登録したページは削除されますのでご注意ください。</p>
<%= form_with model: @shop, local: true do |f| %>
<table class="table">
<%= render 'layouts/error_messages', model: f.object %>
<tr>
<th>
<%= f.label :name, "店名" %>
</th>
<td>
 <%= f.text_field :name, class: "form-control" %>
</td>
</tr>
<tr>
<th>
<%= f.label :name_kana, "店名（かな）" %>
</th>
<td>
 <%= f.text_field :name_kana, class: "form-control" %>
</td>
</tr>

<tr>
<th>
 <%= f.label :prefecture, "都道府県" %></th>
　<td><%= f.select :prefecture, Shop.prefectures.keys, {} %></td>
　</tr>
<tr>
<th>
 <%= f.label :genre_id, "ジャンル" %>
</th>
<td>
 <%= f.select :genre_id, {
     "---":0,
     居酒屋:1,カレー:2,ラーメン:3,焼き肉:4,カフェ:5,鍋:6,寿司:7,
     魚介・海鮮:8,焼き鳥・鳥料理:9,和食:10,天ぷら:11,うどん・そば:12,すき焼き・しゃぶしゃぶ:13,おでん:14,
     お好み焼き・たこ焼き:15,ステーキ・ハンバーグ:16,鉄板焼:17,パスタ・ピザ:18,ハンバーガー:19,洋食:20,
     フレンチ:21,イタリアン:22,西洋各国料理:23,中華料理:24,
     韓国料理:25,バー:26,ファミレス:27,定食:28,丼もの:29,その他:30,
   }, {} %>
</td>

</tr>
<tr>
<th>
<%= f.label :zipcode, "郵便番号" %>
</th>
<td>
 <%= f.text_field :zipcode, class: "form-control" %>
</td>
</tr>

<tr>
<th>
<%= f.label :address, "住所" %>
</th>
<td>
 <%= f.text_field :address, class: "form-control" %>
</td>
</tr>

<tr>
<th>
<%= f.label :phonenumber, "TEL" %>
</th>
<td>
 <%= f.text_field :phonenumber, class: "form-control" %>
</td>
</tr>

<tr>
<th>
<%= f.label :hp, "HP" %>
</th>
<td>
<%= f.text_field :hp, class: "form-control" %>
</td>
</tr>
<tr>
<th>
<%= f.label :regular_holiday, "定休日" %>
</th>
<td>
<%= f.text_field :regular_holiday, class: "form-control" %>
</td>
</tr>
<tr>
<th>
<%= f.label :opning_hours, "営業時間" %>
</th>
<td>
<%= f.text_area :opning_hours, class: "form-control" %>
</td>
</tr>
<tr>
<th>
<%= f.label :acsess, "アクセス" %>
</th>
<td>
<%= f.text_area :acsess, class: "form-control" %>
</td>
</tr>
<tr>
<th>
<%= f.label :parking, "駐車場" %>
</th>
<td>
<%= f.text_field :parking, class: "form-control" %>
</td>
</tr>

<tr>
<th>
<%= f.label :seats, "座席数" %>
</th>
<td>
<%= f.text_field :seats, class: "form-control" %>
</td>
</tr>
<tr>
 <td>画像</td>
 <td><%= f.attachment_field :shop_images_images, multiple: true %></td>
</tr>
<tr>
 <th><%= f.submit %></th>
 </tr>
</table>
<% end %>
</div>

app/views/shops/show.html.erb
<div class="container contents">
  <strong><%= @shop.name %></strong>(<%= @shop.name_kana %>)
  <!--レート表示(round(1)で小数点切り捨て-->
  <h2 class="average-review-rate" data-score=<%= @average_review %>>【評価】<%= @average_review.round(1) %></h2>


  <!--店舗画像スライドショー-->
  <% if @shop.shop_images.present? %>
   <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="3000">
     <ol class="carousel-indicators">
       <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
       <% @shop.shop_images.drop(1).count.times do |index| %>
       <li data-target="#carouselExampleIndicators" data-slide-to="#{index}"></li>
       <% end %>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
        <% @shop.shop_images.first(1).each do |image| %>
          <%= attachment_image_tag image, :image, class: "carousel_image", size: "1000x600"  %>
        <% end %>
        </div>
        <% @shop.shop_images.drop(1).each do |image| %>
          <div class="carousel-item">
          <%= attachment_image_tag image, :image, class: "carousel_image", size: "1000x600" %>
          </div>
        <% end %>
        </div>
        <!--前後のコントロールボタン-->
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
  <% else %>
    <%= image_tag 'no_image.jpg', size: '200x200' %>
  <% end %>
    <%= link_to 'Twitterでお店をシェアする', "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' %>
    <%= link_to "店舗編集",edit_shop_path(@shop) %>
    <h2 class="comment-count"><%= link_to shop_reviews_path(@shop) do %>
    <%= @shop.reviews.count %>件
    <% end %>のレビュー</h2>
    <%= link_to "レビューを投稿する", new_shop_review_path(@shop) %>
    <table  class='table table-bordered'>
    <h1>店舗情報</h1>
    <tr>
      <th class="table-active col-xs-2">店名</th>
      <td><%= @shop.name %>(<%= @shop.name_kana %>)</td>
    </tr>
    <tr>
      <th class="table-active">ジャンル</th>
      <td><%= @genre_name %></td>
    </tr>
    <tr>
      <th class="table-active">住所</th>
      <td><%= @shop.address %></td>
    </tr>
    <tr>
      <th class="table-active">アクセス</th>
      <td><%= @shop.acsess %></td>
    </tr>
    <tr>
      <th class="table-active">営業時間</th>
      <td><%= @shop.opning_hours %></td>
    </tr>
    <tr>
      <th class="table-active">定休日</th>
      <td><%= @shop.regular_holiday %></td>
    </tr>
    <tr>
      <th class="table-active">支払い方法</th>
      <td><%= @shop.payment %></td>
    </tr>
    <tr>
      <th class="table-active">座席数</th>
      <td><%= @shop.seats %></td>
    </tr>
    <tr>
      <th class="table-active">設備</th>
      <td><%= @shop.facility %></td>
    </tr>
    <tr>
      <th class="table-active">駐車場</th>
      <td><%= @shop.parking %></td>
    </tr>
    <tr>
      <th class="table-active">TEL</th>
      <td><%= @shop.phonenumber %></td>
    </tr>
    <tr>
      <th class="table-active">HP</th>
      <td><%= @shop.hp %></td>
    </tr>
    <tr>
      <th class="table-active">都道府県</th>
      <td><%= @shop.prefecture %></td>
    </tr>
    <tr>
      <th class="table-active">郵便番号</th>
      <td><%= @shop.zipcode %></td>
    </tr>
  </table>
<%= link_to "店舗一覧に戻る", shops_path %>
  <!--mapの表示-->
  <style type="text/css">
    #map { height: 200px;
           width: 70%;}
  </style>
<!--googleマップ表示-->
<% if @shop.latitude.present? && @shop.longitude.present? %>
    <div id="map"></div>
    <script type="text/javascript">
    function initMap() {
  // #latitude,longitudeから位置を特定
      var test ={lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 15,
                center: test
                });
      var transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

      var contentString = '住所：<%= @shop.address %>';
      var infowindow = new google.maps.InfoWindow({
        content: contentString
      });
  // #Map上の指定した位置にピンを挿して表示する
      var marker = new google.maps.Marker({
                    position:test,
                    map: map,
                    title: contentString
                   });
         marker.addListener('click', function() {
           infowindow.open(map, marker);
         });
      }
  </script>
  <script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap">
  </script>
<% end %>
  </div>
</div>
<script>
  $('.average-review-rate').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half: true,
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>


</div>