config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get 'quit'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :shops do
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  enum sex: { man:1,woman:2,other:3 }
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit,:destory]

  def show
    @user = User.find(params[:id])
    @shop = Shop.find(params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id), notice:"更新しました"
  end

  def quit
    @user = User.find(params[:id])
    if @user == current_user
      render "destroy"
    else
      redirect_to users_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to :root
  end

  private
  def user_params
    params.require(:user).permit(:name ,:profile_image, :sex, :date_of_birth, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<h1>マイページ編集</h1>
<%= form_with model: @user, local: true do |f| %>
<!--名前-->
<div class="field">
<%= f.label :name, "名前" %>
<%= f.text_field :name, autofocus: true, autocomplete: "name" %>
</div>
<!--プロフィール画像-->
<div class="field">
<%= attachment_image_tag @user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
<%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
</div>
<!--性別 enumで定義-->
<div class="field">
<%= f.label :sex, "性別" %>
<%= f.label :man, "男性" %>
<%= f.radio_button :sex, :man %>
<%= f.label :woman, "女性" %>
<%= f.radio_button :sex, :woman %>
<%= f.label :other, "その他" %>
<%= f.radio_button :sex, :other %>
</div>
<!--生年月日-->
<div class="field">
<%= f.label :date_of_birth, "生年月日" %>
<%= f.date_select :date_of_birth, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1995, 1, 1) %>
</div>
<!--自己紹介-->
<div class="field">
<%= f.label :introduction, "自己紹介" %>
<%= f.text_area :introduction, size: "50x10" %>
</div>
<div class="field">
<%= f.submit "変更を保存" %>
</div>
<%= link_to "退会する", quit_user_path %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container contents">
  <h1>ユーザー一覧</h1>
  <table class="table">
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user_path(user) do %><%= user.name %><% end %></td>
    <td>
      <%= attachment_image_tag user, :profile_image, size: "60x60", fallback: "no_image.jpg", class: "user-img" %>

      </td>
    <td><%= user.sex %></td>
    <td><%= user.date_of_birth %></td>
    <td><%= user.introduction %></td>
  </tr>
<% end %>
</table>
</div>

app/views/users/quit.html.erb
<h1>退会確認画面</h1>
<p>本当に退会しますか？</p>

app/views/users/show.html.erb
<div class="container">
  <div class="raw">

    <div class="mypage-top contents">
      <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "no_image.jpg", class: "user-img" %>
      <%= @user.name %> |
    <%= @user.sex %> |
    <%= @user.date_of_birth %> |
    <%= @user.introduction %>
    <% if current_user.id == @user.id %>
      <%= link_to "編集する", edit_user_path(@user.id) %>
      <% end %>
    </div>
  </div>
  <div class="raw contents">
    <!--投稿日、星を入れたい-->
    レビュー投稿<%= @user.reviews.count %>件
    <% @user.reviews.each do |review| %>
    <table class="table">
      <th>店名 | <%= link_to shop_path(review.shop.id) do %>
      <%= review.shop.name %>
      <% end %></th>
      <th>タイトル | <%= link_to shop_review_path(review.shop.id, review.id) do %>
      <%= review.title %>
      <% end %></th>
      <td>
       評価<%= review.rate %>
     </td>
     <td> <% review.review_images.each do |review_image| %>
    <%= attachment_image_tag review_image, :review_image, size: "100x80" %>
  <% end %></td>
    <% end %>
    </table>
  </div>
</div>