config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get 'quit'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :shops do
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @shop = Shop.find(params[:shop_id])
    @review = Review.new
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @review = current_user.reviews.new(review_params)
    @review.shop_id = @shop.id
    if @review.save
      redirect_to shop_review_path(@shop.id, @review.id), notice:"投稿しました"
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:shop_id])
    @review = Review.find(params[:id])
    if @review.user.id == current_user.id
      render "edit"
    else
      redirect_to shop_reviews_path(@shop.id)
    end
  end

  def update
    @shop = Shop.find(params[:shop_id])
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to shop_review_path(@shop.id, @review.id), notice:"更新しました"
    else
      render :edit
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    @reviews = Review.page(params[:page]).reverse_order
    @review = Review.find(params[:id])
    if @review.user.id == current_user.id
      render "destroy"
    else
      redirect_to shop_reviews_path(@shop.id)
    end
    @review.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to shop_reviews_path(@shop.id)
  end

  def show
    @shop = Shop.find(params[:shop_id])
    @review = Review.find(params[:id])

  end

  def index
    @shop = Shop.find(params[:shop_id])
    # kaminari
    @reviews = Review.page(params[:page]).reverse_order
  end

  private
  def review_params
    params.require(:review).permit(:rate, :review, :shop_id, :use_time, :visit_date, :bgm, :soloist, :space, :volume, :eyes, :busy , :title,  review_images_review_images: [])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<div class="container contents">
  <%= form_with(model:[@shop, @review], local: true) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
      <!--星型のレート機能-->
      <%= f.hidden_field :shop_id, value: @shop.id %>
      <div class="col-md-6 col-md-offset-3">
        <div class="field" id="rate">
          <%= f.label :rate %>
          <%= f.hidden_field :rate, id: :review_rate %>
        </div>
      </div>
      <table class="table">
        <tr>
          <th><%= f.text_area :review, rows:'5', class: "form-control",placeholder: "コメントをここに" %></th>
        </tr>
        <tr>
          <th><%= f.label :bgm, "BGM" %></th>
          <td><%= f.text_field :bgm %></td>
        </tr>
        <tr>
          <th><%= f.label :space, "距離感" %></th>
          <td><%= f.text_field :space %></td>
        </tr>
        <tr>
          <th><%= f.label :volume, "ご飯の量" %></th>
          <td><%= f.text_field :volume %></td>
        </tr>
        <tr>
          <th><%= f.label :eyes, "周りの視線" %></th>
          <td><%= f.text_field :eyes %></td>
        </tr>
        <tr>
          <th><%= f.label :busy, "混雑度" %></th>
          <td> <%= f.text_field :busy %></td>
        </tr>
        <tr>
          <th><%= f.label :soloist, "soloist率(１人客の多さ)" %></th>
          <td><%= f.text_field :soloist %></td>
        </tr>
        <tr>
          <th><%= f.label :use_time, "利用時間帯" %></th>
          <td>
            <div class="field">
              <%= f.label :morning, "朝" %>
              <%= f.radio_button :use_time, :morning %>
              <%= f.label :evening, "昼" %>
              <%= f.radio_button :use_time, :evening %>
              <%= f.label :night, "夜" %>
              <%= f.radio_button :use_time, :night %>
            </div>
          </td>
        </tr>
        <tr>
          <th><%= f.label :visit_date, "訪問日時" %></th>
          <td> <%= f.date_field :visit_date, use_month_numbers: true, start_year: 2020, end_year: (Time.now.year - 10), default: Date.new(2020, 1, 1) %></td>
        </tr>
        <tr>
          <th>画像</th>
          <td><%= f.attachment_field :review_images_review_images, multiple: true %></td>     
        </tr>
      </table>
    </div>
    <%= f.submit "更新する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
    <% end %>
  </div>
</div>

<script>
$('#rate').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[rate]',
});
</script>

app/views/reviews/index.html.erb
<div class="container contents">

    <h1>レビュー一覧</h1>
    <% @shop.reviews.each do |review| %>
    <%= attachment_image_tag review.user, :profile_image, size: "50x50", fallback: "no_image.jpg", class: "user-img" %>
      <%= review.user.name %>
    <div class="review">タイトル
      <%= link_to shop_review_path(@shop.id, review.id) do %>
        <%= review.title %>
      <% end %>
      <%= review.visit_date %>

      <!--レート-->
      <div id="rate<%= review.id%>">評価<%= review.rate %></div>

      <!--レビュー画像-->
      <% if review.review_images.present? %>
        <% review.review_images.each do |review_image| %>
        <%= attachment_image_tag review_image, :review_image, size: "100x100" %>
      <% end %>
      <% else %>
        <%= image_tag 'no_image.jpg', size: '100x100' %>
      <% end %>

      <!--いいね-->
      <div id="favorites_buttons_<%= review.id %>">
        <%= render partial: 'favorites/favorite', locals: {review: review, shop: @shop} %>
      </div>
    </div>

  <script>
    $('#rate<%= review.id%>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      readOnly: true,
      half: true,
      score: <%= review.rate %>,
    });
  </script>
<% end %>
<%= paginate @reviews %>
<%= link_to "お店のページに戻る", shop_path(@shop) %>
</div>

app/views/reviews/new.html.erb
<div class="container contents">
  <h1>レビュー投稿</h1>
  <%= form_with(model:[@shop, @review], local: true) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
      <!--星型のレート機能-->
      <%= f.hidden_field :shop_id, value: @shop.id %>
      <div class="col-md-6 col-md-offset-3">
        <div class="field" id="rate">
          <%= f.label :rate %>
          <%= f.hidden_field :rate, id: :review_rate %>
        </div>
      </div>
      <table class="table">
        <tr>
          <th><%= f.text_area :review, rows:'5', class: "form-control",placeholder: "タイトルとレートのみでも投稿可能です" %></th>
        </tr>
        <tr>
          <th><%= f.label :bgm, "BGM" %></th>
          <td><%= f.text_field :bgm %></td>
        </tr>
        <tr>
          <th><%= f.label :space, "距離感" %></th>
          <td><%= f.text_field :space %></td>
        </tr>
        <tr>
          <th><%= f.label :volume, "ご飯の量" %></th>
          <td><%= f.text_field :volume %></td>
        </tr>
        <tr>
          <th><%= f.label :eyes, "周りの視線" %></th>
          <td><%= f.text_field :eyes %></td>
        </tr>
        <tr>
          <th><%= f.label :busy, "混雑度" %></th>
          <td> <%= f.text_field :busy %></td>
        </tr>
        <tr>
          <th><%= f.label :soloist, "soloist率(１人客の多さ)" %></th>
          <td><%= f.text_field :soloist %></td>
        </tr>
        <tr>
          <th><%= f.label :use_time, "利用時間帯" %></th>
          <td>
            <div class="field">
              <%= f.label :morning, "朝" %>
              <%= f.radio_button :use_time, :morning %>
              <%= f.label :evening, "昼" %>
              <%= f.radio_button :use_time, :evening %>
              <%= f.label :night, "夜" %>
              <%= f.radio_button :use_time, :night %>
            </div>
          </td>
        </tr>
        <tr>
          <th><%= f.label :visit_date, "訪問日時" %></th>
          <td> <%= f.date_field :visit_date, use_month_numbers: true, start_year: 2020, end_year: (Time.now.year - 10), default: Date.new(2020, 1, 1) %></td>
        </tr>
        <tr>
          <th>画像</th>
          <td><%= f.attachment_field :review_images_review_images, multiple: true %></td>
        </tr>
      </table>
    </div>
    <%= f.submit "投稿する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
    <% end %>
  </div>
</div>


<script>
$('#rate').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'review[rate]',
  half: true,
});
</script>

app/views/reviews/show.html.erb
<div class="container contents">
  <h1>レビュー詳細</h1>
  <h2><%= link_to shop_path(@review.shop.id) do %><%= @review.shop.name %><% end %></h2>
   <h2 id="rate<%= @review.id %>">評価<%= @review.rate %></h2>
    <%= link_to user_path(@review.user.id) do %><%= @review.user.name %><% end %>
    <table class="table">
      <tr>
        <th>店名</th>
        <td><%= @shop.name %></td>
      </tr>
      <tr>
        <th>タイトル</th>
        <td><%= @review.title %></td>
      </tr>
      <tr>
        <th>レビュー</th>
        <td><%= @review.review %></td>
      </tr>
      <tr>
        <th>利用時間帯</th>
        <td><%= @review.use_time %></td>
      </tr>
      <tr>
        <th>訪問日</th>
        <td><%= @review.visit_date %></td>
      </tr>
      <tr>
        <th>距離感</th>
        <td><%= @review.space %></td>
      </tr>
      <tr>
        <th>BGM</th>
        <td><%= @review.bgm %></td>
      </tr>
      <tr>
        <th>周りの視線</th>
        <td><%= @review.eyes %></td>
      </tr>
      <tr>
        <th>soloist率(１人客の多さ)</th>
        <td><%= @review.soloist %></td>
      </tr>
      <tr>
        <th>ご飯の量</th>
        <td><%= @review.volume %></td>
      </tr>
      <tr>
        <th>混雑度</th>
        <td><%= @review.busy %></td>
      </tr>
    </table>

    <% @review.review_images.each do |review_image| %>
      <%= attachment_image_tag review_image, :review_image, size: "500x300" %>
    <% end %>
  <!--いいね-->
   <div id="favorites_buttons_<%= @review.id %>">
      <%= render partial: 'favorites/favorite', locals: {review: @review, shop: @shop} %>
    </div>


  <% if current_user.id == @review.user.id %>
  <%= link_to "編集", edit_shop_review_path(@shop.id, @review.id) %>
  <%= link_to "削除", shop_review_path(@review), method: :delete %>
  <% end %>
  <%= link_to "レビュー一覧に戻る", shop_reviews_path(@shop.id) %>
  </div>


<script>
  $('#rate<%= @review.id%>').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    readOnly: true,
    half: true,
    score: <%= @review.rate %>,
  });
</script>