config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get 'quit'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :shops do
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/layouts/_footer.html.erb
<div class="footer text-center">
  <div class="snsicons">
  <div class="sns">SNSで最新情報発信中</div>
<a  href="#" class="icon"><i class="fa fa-twitter"></i></a>
<a href="#" class="icon"><i class="fa fa-instagram"></i></a>
<a href="#" class="icon"><i class="fa fa-facebook"></i></a>
<div>©2020 soloist</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <% if user_signed_in? %>
  <!--ユーザーログイン時-->
  <%= link_to "soloist", :root %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "soloistとは？", homes_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "マイページ", user_path(current_user), class: 'nav-link'  %>
      </li>
      <li class="nav-item">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'  %>
      </li>
       <li class="nav-item">
        <%= link_to "ユーザー一覧", users_path, class: 'nav-link'  %>
      </li>
       <li class="nav-item">
       <%= link_to "店舗登録", new_shop_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item">
       <%= link_to "店舗一覧", shops_path, class: 'nav-link'  %>
      </li>
    </ul>
    <!--検索フォーム-->
     <%= search_form_for @search, url: shops_path do |f| %>
     <%= f.select :prefecture_eq, Shop.prefectures.map %>
      <%= f.search_field :name_or_address_cont_any, placeholder: "店名" %>
      <%= f.submit "検索" %>
      <% end %>
      
    <% else %>
<!--ユーザーログアウト時-->
        <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "soloistとは？", homes_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "新規登録", new_user_registration_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item">
        <%= link_to "ログイン", new_user_session_path, class: 'nav-link'  %>
      </li>
       <li class="nav-item">
        <%= link_to "ユーザー一覧", users_path, class: 'nav-link'  %>
      </li>
       <li class="nav-item">
       <%= link_to "店舗一覧", shops_path, class: 'nav-link'  %>
      </li>
    </ul>
   <%= search_form_for @search, url: shops_path do |f| %>
     <%= f.select :prefecture, Shop.prefectures.keys.to_a, {} %>
      <%= f.search_field :name_or_address_cont_any, placeholder: "店名" %>
      <%= f.submit "検索" %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soloist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--アイコン-->
    <script src="https://kit.fontawesome.com/033f0a5b2b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="body">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <span id="back">
        <a href="#">
          <%= image_tag "arrow.png" %>
        </a>
      </span>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>